# Generated by Django 5.2.3 on 2025-08-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='constraints',
            field=models.TextField(blank=True, help_text='List the constraints for the problem, one per line.'),
        ),
    ]
