# Generated by Django 5.2.3 on 2025-08-19 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_remove_contest_problems'),
        ('problems', '0002_problem_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='contests.contest'),
        ),
        migrations.AddField(
            model_name='problem',
            name='points',
            field=models.IntegerField(default=100, help_text='Points awarded for solving this problem in a contest'),
        ),
    ]
