# Generated by Django 5.2.3 on 2025-08-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_problem_contest_problem_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='input_format',
            field=models.TextField(blank=True, help_text='Description of the input format.', null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_format',
            field=models.TextField(blank=True, help_text='Description of the output format.', null=True),
        ),
    ]
