# Generated by Django 5.2.3 on 2025-08-23 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problem_input_format_problem_output_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='solved_by',
            field=models.ManyToManyField(blank=True, related_name='solved_problems', to=settings.AUTH_USER_MODEL),
        ),
    ]
