# Generated by Django 5.2.3 on 2025-09-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_problem_solved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='time_limit',
            field=models.FloatField(default=1.0, help_text='Time limit in seconds for a solution to run.'),
        ),
    ]
