databases:
  - name: leetcode-clone-db
    plan: free
    databaseName: leetcode_clone_db
    user: leetcode_clone_user

services:
  # --- Backend Service ---
  - type: web
    name: leetcode-clone-backend
    plan: free
    runtime: python
    rootDir: leetcode_clone
    buildCommand: "./build.sh"
    startCommand: "gunicorn leetcode_clone.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: leetcode-clone-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.11.5

  # --- Frontend Service (Corrected) ---
  - type: web
    name: leetcode-clone-frontend
    runtime: static
    rootDir: leetcode-clone-frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: "dist"
    routes:
      # FIX: Correct the source and destination paths
      - type: rewrite
        source: /api/*
        destination: https://leetcode-clone-backend-xkde.onrender.com
      # This rule must come last to act as a fallback
      - type: rewrite
        source: /*
        destination: /index.html