# Generated by Django 5.2.3 on 2025-08-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
