# Generated by Django 5.2.3 on 2025-08-19 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_contest_rules_alter_contest_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='problems',
        ),
    ]
