# Generated by Django 5.2.3 on 2025-08-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_remove_contest_problems'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestparticipant',
            name='last_successful_submission',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
