# Generated by Django 5.2.3 on 2025-08-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_contestparticipant_last_successful_submission'),
        ('problems', '0005_problem_solved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestparticipant',
            name='solved_problems',
            field=models.ManyToManyField(blank=True, to='problems.problem'),
        ),
    ]
